### ISSUE TITLE
I can't get the same result with official result by using the code "python run_ZSSR.py X2_REAL_CONF"

### ISSUE THREAD

**Issue by luohongming** [HarukiYqM/pytorch-ZSSR#1]
Hello, I just git clone your codes and run them by using "python run_ZSSR.py X2_REAL_CONF"
I can't get the same result with official result. The output has artifacts. 
Is anything I did wrong?

**Comment by HarukiYqM** [comment]
Hi, did you compare it with official implementation? In fact, you need be careful since there are pitfalls to use zssr. First thing you may want to try is set kernel_shift_flag=True.

**Comment by luohongming** [comment]
> Hi, did you compare it with official implementation? In fact, you need be careful since there are pitfalls to use zssr. First thing you may want to try is set kernel_shift_flag=True.

Thanks for your reply.
I have fixed this bug and reach the performance of official implementation.

**Comment by tsaiting** [comment]
> > Hi, did you compare it with official implementation? In fact, you need be careful since there are pitfalls to use zssr. First thing you may want to try is set kernel_shift_flag=True.
> 
> Thanks for your reply.
> I have fixed this bug and reach the performance of official implementation.

Can u describe how you fix this problem

**Comment by luohongming** [comment]
> > > Hi, did you compare it with official implementation? In fact, you need be careful since there are pitfalls to use zssr. First thing you may want to try is set kernel_shift_flag=True.
> > 
> > 
> > Thanks for your reply.
> > I have fixed this bug and reach the performance of official implementation.
> 
> Can u describe how you fix this problem

I did not clone these code exactly,  I rewrite ZSSR by using the net architecture and the method creating  training pairs. And I think the key point is the filtering kernel  before dowmsampling. Training longer may help.

**Comment by tsaiting** [comment]
> > > > Hi, did you compare it with official implementation? In fact, you need be careful since there are pitfalls to use zssr. First thing you may want to try is set kernel_shift_flag=True.
> > > 
> > > 
> > > Thanks for your reply.
> > > I have fixed this bug and reach the performance of official implementation.
> > 
> > 
> > Can u describe how you fix this problem
> 
> I did not clone these code exactly, I rewrite ZSSR by using the net architecture and the method creating training pairs. And I think the key point is the filtering kernel before dowmsampling. Training longer may help.

thanks a lot!
